# Generated by Django 5.1.4 on 2025-10-04 10:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('max_zoom_level', models.PositiveIntegerField(verbose_name='Максимальный уровень зума')),
                ('source_url', models.URLField(blank=True, max_length=512, verbose_name='URL источника')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.BigIntegerField(verbose_name='Координата X')),
                ('y', models.BigIntegerField(verbose_name='Координата Y')),
                ('name', models.CharField(max_length=255, verbose_name='Название точки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='app.image', verbose_name='Изображение')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Точка интереса',
                'verbose_name_plural': 'Точки интереса',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeminiInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(verbose_name='Запрос (Prompt)')),
                ('response', models.TextField(verbose_name='Ответ (Response)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gemini_interactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gemini_interactions', to='app.pointofinterest', verbose_name='Точка интереса')),
            ],
            options={
                'verbose_name': 'Взаимодействие с AI',
                'verbose_name_plural': 'Взаимодействия с AI',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='app.comment', verbose_name='Родительский комментарий')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.pointofinterest', verbose_name='Точка интереса')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchableObject',
            fields=[
                ('vector_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID Вектора (в Upstash)')),
                ('name', models.CharField(max_length=255, verbose_name='Название объекта')),
                ('description', models.TextField(verbose_name='Текстовое описание для эмбеддинга')),
                ('object_type', models.CharField(blank=True, max_length=50, verbose_name='Тип объекта (звезда, туманность и т.д.)')),
                ('x', models.BigIntegerField(verbose_name='Координата X центра')),
                ('y', models.BigIntegerField(verbose_name='Координата Y центра')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина (px)')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота (px)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searchable_objects', to='app.image', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Объект для поиска',
                'verbose_name_plural': 'Объекты для поиска',
                'ordering': ['-created_at'],
            },
        ),
    ]
