# Generated by Django 5.1.4 on 2025-10-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='source_file',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/', verbose_name='Файл изображения'),
        ),
        migrations.AddField(
            model_name='image',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Ожидает нарезки'), ('PROCESSING', 'В процессе нарезки'), ('COMPLETED', 'Нарезка завершена'), ('FAILED', 'Ошибка нарезки')], default='PENDING', max_length=20, verbose_name='Статус нарезки'),
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='description',
            field=models.TextField(blank=True, verbose_name='Заметка'),
        ),
        migrations.AlterField(
            model_name='image',
            name='max_zoom_level',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальный уровень зума'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
