# Generated by Django 5.1.4 on 2025-10-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_image_source_file_image_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Файл изображения (.tif)'),
        ),
    ]
