# Generated by Django 5.1.4 on 2025-10-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointofinterest',
            name='owner',
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='owner_name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Имя автора'),
        ),
    ]
