# Generated by Django 5.1.4 on 2025-10-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_pointofinterest_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота (px)'),
        ),
        migrations.AddField(
            model_name='image',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина (px)'),
        ),
    ]
